server:
  port: 8002
mybatis:
  config-location:  classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.mengxuegu.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: microservice-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
